### ISSUE TITLE
Error pulling submodule

### ISSUE THREAD

**Issue by dsagal** [gristlabs/grist-static#1]
I am having trouble with the `git submodule update --init` command.

First issue was `git@github.com: Permission denied (publickey)`, which was due to my not having set up SSH access to github. I set that up following [github instructions](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), and that part now works. (It is cloning  `git@github.com:paulfitz/grist-core`.)

The next error is this:
```
fatal: remote error: upload-pack: not our ref bdaad4c26e761aa6c4705dc28b9d4afe8e4d69c5
Fetched in submodule path 'core', but it did not contain bdaad4c26e761aa6c4705dc28b9d4afe8e4d69c5. Direct fetching of that commit failed.
```
I don't see any mention of this ref anywhere in the checkout, and I am at a loss at why it's looking for it or how to fix it.

**Comment by paulfitz** [comment]
Sorry @dsagal, I somehow never noticed this thread. Do you still have the clone issue?

For the access thing, I remember running into this (but the other way around) and wondering whether there was a friendly way to set this up. Lots of long threads like https://stackoverflow.com/questions/40841882/automatically-access-git-submodules-via-ssh-or-https. If I upstream some of my patches than a relative path might work.

**Comment by dsagal** [comment]
It worked this time!
