### ISSUE TITLE
Synchronous communication without cross-origin isolation

### ISSUE THREAD

**Issue by alexmojaki** [gristlabs/grist-static#2]
Congrats on making this work!!!!! I'm a little sad I wasn't around to help make it happen...

If cross-origin isolation creates problems, there's another method for communication based on service workers. Since you already have a service worker, there shouldn't be much of a downside. I wrote https://github.com/alexmojaki/sync-message for futurecoder to abstract this stuff away. Also check out https://github.com/alexmojaki/pyodide-worker-runner.

**Comment by paulfitz** [comment]
Thanks @alexmojaki ! I ran into your name everywhere in github threads when I was hacking on this :-) The cross-origin isolation is indeed a drag.

**Comment by paulfitz** [comment]
It is possible we may have someone to work on this soon @alexmojaki ;-)
