### ISSUE TITLE
UNIQUE constraint error upon repeated type conversion

### ISSUE THREAD

**Issue by alexmojaki** [gristlabs/grist-static#5]
When I change column type twice in a row, I get `UNIQUE constraint failed: _grist_Tables_column.id failed` as it tries to add the helper columns that the logs say were cleaned up after the previous transform:

![Screenshot from 2023-06-12 17-28-41](https://github.com/gristlabs/grist-static/assets/3627481/6996c23b-a255-456e-b267-42908e14ff06)

**Comment by paulfitz** [comment]
Should have been fixed by https://github.com/gristlabs/grist-core/pull/566, will reach grist-static soon.
